export const CITY = [
  'Achlum',
  'Acht',
  'Achter het Klooster',
  'Achter t Hout',
  'Achterberg',
  'Achterbos',
  'Achterbosch',
  'Blaaksedijk',
  'Bladel',
  'Blaker',
  'Blankenberg',
  'Blankenham',
  'Blankeweer',
  'Blaricum',
  'Blauw',
  'Blauwe Hand',
  'Blauwe Sluis',
  'Coevorden',
  'Coldenhove',
  'Colijnsplaat',
  'Collendoorn',
  'Collendoornerveen',
  'Colmont',
  'Colmschate',
  'Dodewaard',
  'Doenrade',
  'Doesburg',
  'Doetinchem',
  'Doeveren',
  'Doezum',
  'Dokkum',
  'Dokkumer Nieuwe Zijlen',
  'Doldersum',
  'Domburg',
];
