export const STREETS = [
  'Transvaalstraat',
  'Linnaeusstraat',
  'Middenweg',
  'A A de Lannoy-Willemsstr',
  'A Eduardine Kokplnts',
  'A. Reitsmakade',
  'A.A.H. Struijckenkade',
  'A.J. Koejemansstraat',
  'A.J. Krophollerstraat',
  'A.M. de Jongstraat',
  'A.S. Onderwijzerhof',
  'A.W. Grootehof',
  'Aaf Bouberstraat',
  'Aagtdorperpad',
  'Aakstraat',
  'Aalsmeerplein',
  'Aalsmeerweg',
  'Aambeeldstraat',
];
